export const BLOG = {
  page: "blog-goa-page",
  navBookBtn: "nav-book-btn",
  navBrand: "nav-brand",
  heroHeadline: "hero-headline",
  heroCtaPrimary: "hero-cta-primary",
  heroCtaSecondary: "hero-cta-secondary",
  scrollIndicator: "hero-scroll-indicator",
  tocDesktop: "toc-desktop",
  tocMobile: "toc-mobile",
  tocLink: (id) => `toc-link-${id}`,
  serviceCard: (id) => `service-card-${id}`,
  reelCard: "service-reel-highlight",
  locationCard: (id) => `location-card-${id}`,
  packageCard: (id) => `package-card-${id}`,
  packageCtaCustom: "package-cta-custom",
  faqItem: (id) => `faq-item-${id}`,
  finalCtaBook: "final-cta-book",
  finalCtaWhatsapp: "final-cta-whatsapp",
  finalCtaEmail: "final-cta-email",
  footer: "site-footer",
};
